spring:
  profiles:
    active: h2
  datasource:
    h2:
      url: jdbc:h2:file:~/figures-api
      driverClassName: org.h2.Driver
      username: sa
      password: password
    mysql:
      url: jdbc:mysql://localhost:3306/mydatabase
      driverClassName: com.mysql.cj.jdbc.Driver
      username: myuser
      password: mypassword
  jpa:
    h2:
      database-platform: org.hibernate.dialect.H2Dialect
    mysql:
      database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
